#pragma once

#include "./ast/ast_string.h"
#include "./ast/block.h"
#include "./ast/bool.h"
#include "./ast/call.h"
#include "./ast/expr.h"
#include "./ast/fn_literal.h"
#include "./ast/ident.h"
#include "./ast/if.h"
#include "./ast/infix.h"
#include "./ast/int.h"
#include "./ast/let.h"
#include "./ast/node.h"
#include "./ast/prefix.h"
#include "./ast/program.h"
#include "./ast/return.h"